version: "3"

services:

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - mysql
      - php

  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql

  composer:
    build:
      dockerfile: docker/composer/Dockerfile
    volumes:
      - db_data:/var/www/html

volumes:
  db_data:
